Repository moidot/backend, pull requests merged in 2023-07, with the labels that each got.

#26 feat: 로그인 로직 구현
  .gitignore
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/com/moim/backend/domain/user/controller/UserController.java
  src/main/java/com/moim/backend/domain/user/entity/BookmarkPlace.java
  src/main/java/com/moim/backend/domain/user/entity/User.java
  src/main/java/com/moim/backend/domain/user/repository/UserRepository.java
  src/main/java/com/moim/backend/domain/user/request/UserRequest.java
  src/main/java/com/moim/backend/domain/user/response/UserResponse.java
  src/main/java/com/moim/backend/domain/user/service/UserService.java
  src/main/java/com/moim/backend/global/auth/Login.java
  src/main/java/com/moim/backend/global/auth/LoginArgumentResolver.java
  src/main/java/com/moim/backend/global/auth/jwt/JwtService.java
  src/main/java/com/moim/backend/global/config/WebConfig.java
  src/test/java/com/moim/backend/docs/user/UserControllerDocsTest.java
Labels: feature

#27 refactor: jwt 예외 처리 로직 추가
  src/main/java/com/moim/backend/domain/user/controller/UserController.java
  src/main/java/com/moim/backend/domain/user/request/UserRequest.java
  src/main/java/com/moim/backend/global/auth/jwt/JwtService.java
  src/main/java/com/moim/backend/global/common/CustomResponseEntity.java
  src/main/java/com/moim/backend/global/common/Result.java
  src/main/java/com/moim/backend/global/common/exception/CommonRestExceptionHandler.java
Labels: feature

#28 feat : 모임 API 유저 연동 및 User 예약어로 인한 Entity 이름 변경
  src/docs/asciidoc/api/common/statusDetail.adoc
  src/main/java/com/moim/backend/domain/space/controller/GroupController.java
  src/main/java/com/moim/backend/domain/space/entity/Groups.java
  src/main/java/com/moim/backend/domain/space/request/GroupRequest.java
  src/main/java/com/moim/backend/domain/space/request/GroupServiceRequest.java
  src/main/java/com/moim/backend/domain/space/response/GroupResponse.java
  src/main/java/com/moim/backend/domain/space/service/GroupService.java
  src/main/java/com/moim/backend/domain/user/controller/UserController.java
  src/main/java/com/moim/backend/domain/user/entity/BookmarkPlace.java
  src/main/java/com/moim/backend/domain/user/entity/Users.java
  src/main/java/com/moim/backend/domain/user/repository/UserRepository.java
  src/main/java/com/moim/backend/domain/user/request/UserRequest.java
  src/main/java/com/moim/backend/domain/user/service/UserService.java
  src/main/java/com/moim/backend/global/auth/LoginArgumentResolver.java
  src/main/java/com/moim/backend/global/auth/jwt/JwtService.java
  src/main/java/com/moim/backend/global/config/WebConfig.java
  src/test/java/com/moim/backend/docs/space/GroupControllerDocsTest.java
  src/test/java/com/moim/backend/docs/user/UserControllerDocsTest.java
  src/test/java/com/moim/backend/domain/space/controller/GroupControllerTest.java
  src/test/java/com/moim/backend/domain/space/service/GroupServiceTest.java
Labels: feature

#30 refactor: @Login 어노테이션이 있는 파라미터가 존재하는 경우 검증 과정 거치도록 수정
  src/main/java/com/moim/backend/global/auth/LoginInterceptor.java
  src/main/java/com/moim/backend/global/config/WebConfig.java
Labels: refactor

#32 fix: 동일한 배포그룹이 있을 경우 덮어쓰기하도록 설정
  appspec.yml
Labels: bug

#48 fix: ClassCastException 해결(LoginInterceptor에서 토큰 검증이 필요한지 확인하는 과정에서 발생)
  src/main/java/com/moim/backend/global/auth/LoginInterceptor.java
Labels: bug

#45 feat: 모임 추천 지역 조회하기 API 개발
  src/docs/asciidoc/api/space/group.adoc
  src/main/java/com/moim/backend/domain/space/Repository/GroupRepository.java
  src/main/java/com/moim/backend/domain/space/Repository/ParticipationRepository.java
  src/main/java/com/moim/backend/domain/space/controller/GroupController.java
  src/main/java/com/moim/backend/domain/space/response/MiddlePoint.java
  src/main/java/com/moim/backend/domain/space/service/GroupService.java
  src/main/java/com/moim/backend/domain/subway/repository/SubwayRepository.java
  src/main/java/com/moim/backend/domain/subway/response/BestSubway.java
  src/main/java/com/moim/backend/domain/subway/response/BestSubwayInterface.java
  src/test/java/com/moim/backend/docs/space/GroupControllerDocsTest.java
  src/test/java/com/moim/backend/domain/space/service/GroupServiceTest.java
Labels: docs, feature

#50 feat : 모임 삭제하기 API
  src/docs/asciidoc/api/common/statusDetail.adoc
  src/docs/asciidoc/api/space/group.adoc
  src/main/java/com/moim/backend/domain/space/controller/GroupController.java
  src/main/java/com/moim/backend/domain/space/service/GroupService.java
  src/main/java/com/moim/backend/global/common/Result.java
  src/test/java/com/moim/backend/docs/space/GroupControllerDocsTest.java
  src/test/java/com/moim/backend/domain/space/controller/GroupControllerTest.java
  src/test/java/com/moim/backend/domain/space/service/GroupServiceTest.java
Labels: docs, feature

#51 feat : 내 모임 확인하기 API 구현 / QueryDSL 세팅 / 모임 참여하기 로직 변경
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/api/space/group.adoc
  src/main/generated/com/moim/backend/domain/groupvote/entity/QSelectPlace.java
  src/main/generated/com/moim/backend/domain/groupvote/entity/QVote.java
  src/main/generated/com/moim/backend/domain/groupvote/entity/QVotePlace.java
  src/main/generated/com/moim/backend/domain/hotplace/entity/QHotPlace.java
  src/main/generated/com/moim/backend/domain/space/entity/QBestPlace.java
  src/main/generated/com/moim/backend/domain/space/entity/QGroups.java
  src/main/generated/com/moim/backend/domain/space/entity/QParticipation.java
  src/main/generated/com/moim/backend/domain/subway/entity/QSubway.java
  src/main/generated/com/moim/backend/domain/user/entity/QBookmarkPlace.java
  src/main/generated/com/moim/backend/domain/user/entity/QUsers.java
  src/main/java/com/moim/backend/domain/space/Repository/ParticipationRepository.java
  src/main/java/com/moim/backend/domain/space/controller/GroupController.java
  src/main/java/com/moim/backend/domain/space/entity/BestPlace.java
  src/main/java/com/moim/backend/domain/space/entity/Groups.java
  src/main/java/com/moim/backend/domain/space/repository/BestPlaceRepository.java
  src/main/java/com/moim/backend/domain/space/repository/GroupCustomRepository.java
  src/main/java/com/moim/backend/domain/space/repository/GroupRepository.java
  src/main/java/com/moim/backend/domain/space/repository/GroupRepositoryImpl.java
  src/main/java/com/moim/backend/domain/space/response/GroupResponse.java
  src/main/java/com/moim/backend/domain/space/service/GroupService.java
  src/main/java/com/moim/backend/domain/subway/entity/Subway.java
  src/main/java/com/moim/backend/domain/subway/repository/SubwayCustomRepository.java
  src/main/java/com/moim/backend/domain/subway/repository/SubwayRepository.java
  src/main/java/com/moim/backend/domain/subway/repository/SubwayRepositoryImpl.java
  src/test/java/com/moim/backend/TestQueryDSLConfig.java
  src/test/java/com/moim/backend/docs/space/GroupControllerDocsTest.java
  src/test/java/com/moim/backend/domain/admin/service/VersionServiceTest.java
  src/test/java/com/moim/backend/domain/space/controller/GroupControllerTest.java
  src/test/java/com/moim/backend/domain/space/repository/GroupRepositoryTest.java
  src/test/java/com/moim/backend/domain/space/service/GroupServiceTest.java
  src/test/java/com/moim/backend/domain/subway/repository/SubwayRepositoryTest.java
  src/test/java/com/moim/backend/global/auth/jwt/JwtServiceTest.java
Labels: docs, feature, ci / cd

#55 feat: kakao login
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/com/moim/backend/domain/user/config/KakaoProperties.java
  src/main/java/com/moim/backend/domain/user/controller/UserController.java
  src/main/java/com/moim/backend/domain/user/request/UserRequest.java
  src/main/java/com/moim/backend/domain/user/response/KakaoTokenResponse.java
  src/main/java/com/moim/backend/domain/user/response/KakaoUserResponse.java
  src/main/java/com/moim/backend/domain/user/response/UserResponse.java
  src/main/java/com/moim/backend/domain/user/service/UserService.java
  src/main/java/com/moim/backend/global/auth/jwt/JwtService.java
  src/test/java/com/moim/backend/docs/user/UserControllerDocsTest.java
Labels: docs, feature

#61 feat: 중복 참여 방지 로직 추가
  src/main/java/com/moim/backend/domain/space/repository/ParticipationRepository.java
  src/main/java/com/moim/backend/domain/space/request/GroupRequest.java
  src/main/java/com/moim/backend/domain/space/request/GroupServiceRequest.java
  src/main/java/com/moim/backend/domain/space/service/GroupService.java
  src/main/java/com/moim/backend/global/common/Result.java
  src/main/java/com/moim/backend/global/common/exception/CommonRestExceptionHandler.java
  src/test/java/com/moim/backend/docs/space/GroupControllerDocsTest.java
  src/test/java/com/moim/backend/domain/space/controller/GroupControllerTest.java
  src/test/java/com/moim/backend/domain/space/service/GroupServiceTest.java
Labels: test, enhancement
